PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS player_match_statistics_extended (
  id INTEGER PRIMARY KEY,
  match_id TEXT NOT NULL,
  player_id TEXT NOT NULL,
  club_id TEXT NOT NULL,
  provider_fixture_id TEXT,
  provider_player_id TEXT,
  started INTEGER DEFAULT 0,
  substitute INTEGER DEFAULT 0,
  minutes INTEGER DEFAULT 0,
  position TEXT,
  rating REAL,
  captain INTEGER DEFAULT 0,
  goals INTEGER DEFAULT 0,
  assists INTEGER DEFAULT 0,
  goals_conceded INTEGER,
  saves INTEGER,
  shots_total INTEGER,
  shots_on_target INTEGER,
  passes_total INTEGER,
  passes_key INTEGER,
  pass_accuracy_pct REAL,
  tackles_total INTEGER,
  tackles_blocks INTEGER,
  tackles_interceptions INTEGER,
  duels_total INTEGER,
  duels_won INTEGER,
  dribbles_attempts INTEGER,
  dribbles_success INTEGER,
  dribbles_past INTEGER,
  fouls_drawn INTEGER,
  fouls_committed INTEGER,
  yellow_cards INTEGER DEFAULT 0,
  red_cards INTEGER DEFAULT 0,
  penalty_won INTEGER DEFAULT 0,
  penalty_committed INTEGER DEFAULT 0,
  penalty_scored INTEGER DEFAULT 0,
  penalty_missed INTEGER DEFAULT 0,
  penalty_saved INTEGER DEFAULT 0,
  source_name TEXT NOT NULL,
  acquired_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(match_id, player_id, source_name),
  FOREIGN KEY(match_id) REFERENCES matches(match_id),
  FOREIGN KEY(player_id) REFERENCES players(player_id),
  FOREIGN KEY(club_id) REFERENCES clubs(club_id)
);

CREATE TABLE IF NOT EXISTS player_season_statistics_extended (
  id INTEGER PRIMARY KEY,
  player_id TEXT NOT NULL,
  season_id INTEGER NOT NULL,
  club_id TEXT NOT NULL,
  competition_id INTEGER NOT NULL,
  appearances INTEGER DEFAULT 0,
  starts INTEGER DEFAULT 0,
  substitute_appearances INTEGER DEFAULT 0,
  minutes INTEGER DEFAULT 0,
  avg_rating REAL,
  goals INTEGER DEFAULT 0,
  assists INTEGER DEFAULT 0,
  goals_conceded INTEGER,
  saves INTEGER,
  shots_total INTEGER,
  shots_on_target INTEGER,
  passes_total INTEGER,
  passes_key INTEGER,
  pass_accuracy_pct REAL,
  tackles_total INTEGER,
  blocks INTEGER,
  interceptions INTEGER,
  duels_total INTEGER,
  duels_won INTEGER,
  dribbles_attempts INTEGER,
  dribbles_success INTEGER,
  fouls_drawn INTEGER,
  fouls_committed INTEGER,
  yellow_cards INTEGER DEFAULT 0,
  red_cards INTEGER DEFAULT 0,
  penalties_won INTEGER DEFAULT 0,
  penalties_committed INTEGER DEFAULT 0,
  penalties_scored INTEGER DEFAULT 0,
  penalties_missed INTEGER DEFAULT 0,
  penalties_saved INTEGER DEFAULT 0,
  goals_per90 REAL,
  assists_per90 REAL,
  shots_per90 REAL,
  key_passes_per90 REAL,
  tackles_per90 REAL,
  interceptions_per90 REAL,
  duels_won_pct REAL,
  dribble_success_pct REAL,
  source_name TEXT NOT NULL,
  methodology_version TEXT NOT NULL DEFAULT 'block3-v1',
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(player_id, season_id, club_id, competition_id, source_name),
  FOREIGN KEY(player_id) REFERENCES players(player_id),
  FOREIGN KEY(season_id) REFERENCES seasons(season_id),
  FOREIGN KEY(club_id) REFERENCES clubs(club_id),
  FOREIGN KEY(competition_id) REFERENCES competitions(competition_id)
);

CREATE TABLE IF NOT EXISTS import_runs (
  import_run_id INTEGER PRIMARY KEY,
  block_name TEXT NOT NULL,
  source_name TEXT NOT NULL,
  season_label TEXT,
  started_at TEXT NOT NULL,
  completed_at TEXT,
  status TEXT NOT NULL,
  records_received INTEGER DEFAULT 0,
  records_inserted INTEGER DEFAULT 0,
  records_updated INTEGER DEFAULT 0,
  records_skipped INTEGER DEFAULT 0,
  error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_pmse_player ON player_match_statistics_extended(player_id, match_id);
CREATE INDEX IF NOT EXISTS idx_pmse_match ON player_match_statistics_extended(match_id, club_id);
CREATE INDEX IF NOT EXISTS idx_psse_player_season ON player_season_statistics_extended(player_id, season_id);
CREATE INDEX IF NOT EXISTS idx_import_runs_block ON import_runs(block_name, season_label, status);
